print("13 % 3 = ", 13%3, "(qoldiq)")
print()
print("uchni beshinshi darajasi bu -", 3**5)
print()
print("9ni ildizi bu - ", 9**0.5)
print()
print("har kuni 30 sahifa kitob oqilsa, bir haftada -", 30*7, "ta sahifa oqiladi")
print()
print("1 ta non 3000 bolsa, 1 ta sut 5000 bolsa, 1 kg meva 7000 bolsa:")
print("3 ta non, 2 ta sut va 4 kg meva jami -", (3*3000)+(2*5000)+4*7000, "som boladi")
print()
print("bir kunda ertalab 18km va kechqurun 18km masofa yurilsa:")
print("bir haftada - ", 18 * 14, "km masofa yuriladi")
print()
print("telefonda quvvat 80%, va har soatda 15% quvvat ketadi:")
print("3 sogotda telefonda -", 80-(15*3), "% quvvat qoladi")
print()
print("4 inson uchun 4 ta pizza zakaz qilingan, har biri 25000 som - shunda har bir inson 25 000 som tolaydi")
print()
print("Ohirgi misolni ozgartirilgani:")
print("3 ta inson uchun 4 pizza zakaz qilingan. har biri 25000 somdan")
print("shunda har bir inson -", (25000*4)//3, "somdan beradi")
print("va kimdur 100 som qoshadi)")